# Generated by Django 3.2.5 on 2021-11-29 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('IdMenu', models.AutoField(primary_key=True, serialize=False)),
                ('Designation', models.CharField(max_length=50)),
                ('DateModifMenu', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('IdRestau', models.AutoField(primary_key=True, serialize=False)),
                ('NomRestau', models.CharField(max_length=50)),
                ('Adresse', models.CharField(max_length=200)),
                ('EmailRestau', models.EmailField(max_length=254)),
                ('NumeroRestau', models.CharField(max_length=12)),
                ('Logo', models.ImageField(upload_to='images/restaurant')),
                ('DateModifRestau', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('IdTable', models.AutoField(primary_key=True, serialize=False)),
                ('Capacity', models.IntegerField()),
                ('Dispo', models.BooleanField()),
                ('IdRestau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('Idplat', models.AutoField(primary_key=True, serialize=False)),
                ('NomPlat', models.CharField(max_length=50)),
                ('PrixPlat', models.FloatField()),
                ('Description', models.TextField()),
                ('DateModifPlat', models.DateField()),
                ('IdMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='IdRestau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.restaurant'),
        ),
        migrations.CreateModel(
            name='CodeQR',
            fields=[
                ('IdCode', models.AutoField(primary_key=True, serialize=False)),
                ('Url', models.CharField(max_length=200)),
                ('IdRestau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.restaurant')),
                ('IdTable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RestaurantApp.table')),
            ],
        ),
    ]
